### ISSUE TITLE
Run make deploy is Error

### ISSUE THREAD

**Issue by lisa-sum** [trstringer/otel-shopping-cart#2]
Hello, I read the first part of the tutorial at https://trstringer.com/otel-part1-intro/
I get an error when I run make deploy in this example:
What's Next?
View a summary of image vulnerabilities and recommendations → docker scout quickview
docker push localhost:5001/otel-shopping-cart-cart:latest
The push refers to repository [localhost:5001/otel-shopping-cart-cart]
Get "http://localhost:5001/v2/": dial tcp [::1]:5001: connect: connection refused
make: *** [push-images] Error 1

I have installed kind (https://kind.sigs.k8s.io/) and using a kind of create cluster create the cluster
And in https://github.com/open-telemetry/opentelemetry-collector/releases/download/cmd%2Fbuilder%2Fv0.88.0/ocb_0.88.0_darwin_ar ocb is installed on m64
Using docker ps only:
CONTAINER ID   IMAGE                  COMMAND                  CREATED       STATUS       PORTS                       NAMES
ce14b54c0bae   kindest/node:v1.27.3   "/usr/local/bin/entr…"   2 hours ago   Up 2 hours   127.0.0.1:52024->6443/tcp   kind-control-plane

**Comment by trstringer** [comment]
Sorry for the delay! This is because you need to have a local registry for the images. [Here is a script to run kind with a local registry](https://kind.sigs.k8s.io/docs/user/local-registry/).

**Comment by trstringer** [comment]
Closing this issue now, but please reopen if that doesn't help!
